# Canada Workers Benefit Parameters
# Income Tax Act Section 122.7
#
# Reference: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/cwb.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/section-122.7.html

description: "The Canada Workers Benefit (CWB) is a refundable tax credit to help individuals and families who are working and earning a low income."

# Basic benefit - maximum amounts
basic:
  max_single:
    description: "Maximum CWB basic benefit for a single individual."
    unit: CAD
    period: year
    label: "CWB Maximum (Single)"
    reference: "ITA 122.7(1.1)(a)"
    values:
      - date: 2024-01-01
        value: 1518
        reference: "CRA CWB 2024"
      - date: 2023-01-01
        value: 1428
        reference: "CRA CWB 2023"
      - date: 2022-01-01
        value: 1395
        reference: "CRA CWB 2022"
      - date: 2021-01-01
        value: 1395
        reference: "CRA CWB 2021"
      - date: 2019-01-01
        value: 1355
        reference: "CRA CWB 2019"

  max_family:
    description: "Maximum CWB basic benefit for a family (individual with spouse or dependant)."
    unit: CAD
    period: year
    label: "CWB Maximum (Family)"
    reference: "ITA 122.7(1.1)(b)"
    values:
      - date: 2024-01-01
        value: 2616
        reference: "CRA CWB 2024"
      - date: 2023-01-01
        value: 2461
        reference: "CRA CWB 2023"
      - date: 2022-01-01
        value: 2403
        reference: "CRA CWB 2022"
      - date: 2021-01-01
        value: 2403
        reference: "CRA CWB 2021"

  phase_in_threshold:
    description: "Working income threshold above which CWB basic benefit starts to phase in."
    unit: CAD
    period: year
    label: "CWB Phase-in Threshold"
    reference: "ITA 122.7(1)"
    values:
      - date: 2019-01-01
        value: 3000
        reference: "ITA 122.7(1)"

  phase_in_rate:
    description: "Rate at which CWB basic benefit phases in for income above the threshold."
    unit: rate
    period: year
    label: "CWB Phase-in Rate"
    reference: "ITA 122.7(1)"
    values:
      - date: 2019-01-01
        value: 0.27
        reference: "ITA 122.7(1) - 27%"

  phase_out_threshold_single:
    description: "Net income threshold for single individuals above which CWB basic benefit phases out."
    unit: CAD
    period: year
    label: "CWB Phase-out Threshold (Single)"
    reference: "ITA 122.7(1.1)"
    values:
      - date: 2024-01-01
        value: 25036
        reference: "CRA CWB 2024"
      - date: 2023-01-01
        value: 23495
        reference: "CRA CWB 2023"
      - date: 2022-01-01
        value: 22944
        reference: "CRA CWB 2022"
      - date: 2021-01-01
        value: 22944
        reference: "CRA CWB 2021"

  phase_out_threshold_family:
    description: "Net income threshold for families above which CWB basic benefit phases out."
    unit: CAD
    period: year
    label: "CWB Phase-out Threshold (Family)"
    reference: "ITA 122.7(1.1)"
    values:
      - date: 2024-01-01
        value: 28494
        reference: "CRA CWB 2024"
      - date: 2023-01-01
        value: 26805
        reference: "CRA CWB 2023"
      - date: 2022-01-01
        value: 26177
        reference: "CRA CWB 2022"
      - date: 2021-01-01
        value: 26177
        reference: "CRA CWB 2021"

  phase_out_rate:
    description: "Rate at which CWB basic benefit phases out for income above the threshold."
    unit: rate
    period: year
    label: "CWB Phase-out Rate"
    reference: "ITA 122.7(1.1)"
    values:
      - date: 2019-01-01
        value: 0.15
        reference: "ITA 122.7(1.1) - 15%"

# Disability supplement
disability:
  max_amount:
    description: "Maximum CWB disability supplement for eligible individuals."
    unit: CAD
    period: year
    label: "CWB Disability Maximum"
    reference: "ITA 122.7(1.2)"
    values:
      - date: 2024-01-01
        value: 784
        reference: "CRA CWB 2024"
      - date: 2023-01-01
        value: 737
        reference: "CRA CWB 2023"
      - date: 2022-01-01
        value: 720
        reference: "CRA CWB 2022"
      - date: 2021-01-01
        value: 720
        reference: "CRA CWB 2021"

  phase_in_threshold:
    description: "Working income threshold above which disability supplement phases in."
    unit: CAD
    period: year
    label: "CWB Disability Phase-in Threshold"
    reference: "ITA 122.7(1.2)"
    values:
      - date: 2019-01-01
        value: 1150
        reference: "ITA 122.7(1.2)"

  phase_in_rate:
    description: "Rate at which disability supplement phases in."
    unit: rate
    period: year
    label: "CWB Disability Phase-in Rate"
    reference: "ITA 122.7(1.2)"
    values:
      - date: 2019-01-01
        value: 0.27
        reference: "ITA 122.7(1.2) - 27%"

  phase_out_rate:
    description: "Rate at which disability supplement phases out."
    unit: rate
    period: year
    label: "CWB Disability Phase-out Rate"
    reference: "ITA 122.7(1.2)"
    values:
      - date: 2019-01-01
        value: 0.15
        reference: "ITA 122.7(1.2) - 15%"

# Age requirements
age:
  minimum:
    description: "Minimum age to claim CWB (unless have spouse or dependant)."
    unit: years
    period: eternity
    label: "CWB Minimum Age"
    reference: "ITA 122.7(1)"
    values:
      - date: 2019-01-01
        value: 19
        reference: "ITA 122.7(1)"

# Incarceration limit
incarceration:
  max_days:
    description: "Maximum days incarcerated during the year to remain eligible."
    unit: days
    period: year
    label: "CWB Maximum Incarceration Days"
    reference: "ITA 122.7(3)(b)"
    values:
      - date: 2019-01-01
        value: 90
        reference: "ITA 122.7(3)(b) - 90 days or more disqualifies"
