# Employment Insurance Parameters
# Employment Insurance Act (S.C. 1996, c. 23)
#
# Reference: https://www.canada.ca/en/services/benefits/ei.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/E-5.6/

description: "Employment Insurance (EI) provides temporary income support for workers who lose their jobs, as well as special benefits for sickness, maternity, parental, and caregiving situations."

# Maximum insurable earnings
max_insurable_earnings:
  annual:
    description: "Maximum annual insurable earnings for EI premium and benefit calculations."
    unit: CAD
    period: year
    label: "EI Maximum Insurable Earnings"
    reference: "EI Act Section 4"
    values:
      - date: 2024-01-01
        value: 63200
        reference: "Canada Gazette 2023"
      - date: 2023-01-01
        value: 61500
        reference: "Canada Gazette 2022"
      - date: 2022-01-01
        value: 60300
        reference: "Canada Gazette 2021"
      - date: 2021-01-01
        value: 56300
        reference: "Canada Gazette 2020"

  weekly:
    description: "Maximum weekly insurable earnings."
    unit: CAD
    period: week
    label: "EI Maximum Weekly Earnings"
    reference: "EI Act Section 4"
    values:
      - date: 2024-01-01
        value: 1215  # $63,200 / 52
        reference: "Derived from annual MIE"
      - date: 2023-01-01
        value: 1183  # $61,500 / 52
        reference: "Derived from annual MIE"

# Premium rates
premium:
  employee_rate:
    description: "EI premium rate for employees (outside Quebec)."
    unit: rate
    period: year
    label: "EI Employee Premium Rate"
    reference: "EI Act Section 67"
    values:
      - date: 2024-01-01
        value: 0.0166
        reference: "1.66% for 2024"
      - date: 2023-01-01
        value: 0.0163
        reference: "1.63% for 2023"
      - date: 2022-01-01
        value: 0.0158
        reference: "1.58% for 2022"

  employee_rate_quebec:
    description: "EI premium rate for employees in Quebec (lower due to QPIP)."
    unit: rate
    period: year
    label: "EI Employee Rate (Quebec)"
    reference: "EI Act Section 67, EI Regulations"
    values:
      - date: 2024-01-01
        value: 0.0132
        reference: "1.32% for 2024 (Quebec)"
      - date: 2023-01-01
        value: 0.0127
        reference: "1.27% for 2023 (Quebec)"

  employer_multiplier:
    description: "Employer premium is this multiple of employee premium."
    unit: rate
    period: eternity
    label: "EI Employer Multiplier"
    reference: "EI Act Section 68"
    values:
      - date: 1996-01-01
        value: 1.4
        reference: "EI Act Section 68(1)"

  max_employee_annual:
    description: "Maximum annual EI premium for an employee (outside Quebec)."
    unit: CAD
    period: year
    label: "EI Maximum Employee Premium"
    reference: "EI Act"
    values:
      - date: 2024-01-01
        value: 1049.12
        reference: "$63,200 * 1.66%"
      - date: 2023-01-01
        value: 1002.45
        reference: "$61,500 * 1.63%"

  max_employee_annual_quebec:
    description: "Maximum annual EI premium for an employee in Quebec."
    unit: CAD
    period: year
    label: "EI Maximum Premium (Quebec)"
    reference: "EI Act"
    values:
      - date: 2024-01-01
        value: 834.24
        reference: "$63,200 * 1.32%"
      - date: 2023-01-01
        value: 781.05
        reference: "$61,500 * 1.27%"

# Benefit rates
benefit:
  standard_rate:
    description: "Standard EI benefit rate as percentage of average insurable earnings."
    unit: rate
    period: eternity
    label: "EI Benefit Rate"
    reference: "EI Act Section 14"
    values:
      - date: 1996-01-01
        value: 0.55
        reference: "55% of average insurable earnings"

  extended_parental_rate:
    description: "Benefit rate for extended parental benefits."
    unit: rate
    period: eternity
    label: "EI Extended Parental Rate"
    reference: "EI Act Section 12"
    values:
      - date: 2017-12-03
        value: 0.33
        reference: "33% for extended parental option"

  family_supplement_max_rate:
    description: "Maximum benefit rate with family supplement."
    unit: rate
    period: eternity
    label: "EI Family Supplement Max Rate"
    reference: "EI Act Section 16"
    values:
      - date: 1996-01-01
        value: 0.80
        reference: "Up to 80% with family supplement"

  max_weekly:
    description: "Maximum weekly EI benefit amount."
    unit: CAD
    period: week
    label: "EI Maximum Weekly Benefit"
    reference: "EI Act Section 14"
    values:
      - date: 2024-01-01
        value: 668
        reference: "$63,200 / 52 * 55%"
      - date: 2023-01-01
        value: 650
        reference: "$61,500 / 52 * 55%"

# Hours requirements
hours:
  minimum_regular:
    description: "Minimum insurable hours required for regular EI benefits."
    unit: hours
    period: year
    label: "EI Minimum Hours"
    reference: "EI Act Section 7"
    values:
      - date: 1996-01-01
        value: 420
        reference: "420-700 hours depending on regional unemployment rate"

  maximum_regular:
    description: "Maximum insurable hours required for regular EI in high unemployment regions."
    unit: hours
    period: year
    label: "EI Maximum Hours Required"
    reference: "EI Act Section 7"
    values:
      - date: 1996-01-01
        value: 700
        reference: "700 hours in regions with 6% or less unemployment"

  special_benefits:
    description: "Hours required for special benefits (maternity, parental, sickness)."
    unit: hours
    period: year
    label: "EI Special Benefits Hours"
    reference: "EI Act Section 7"
    values:
      - date: 1996-01-01
        value: 600
        reference: "600 hours for special benefits"

# Benefit duration
duration:
  maternity_weeks:
    description: "Maximum weeks of maternity benefits."
    unit: weeks
    period: eternity
    label: "EI Maternity Weeks"
    reference: "EI Act Section 22"
    values:
      - date: 1996-01-01
        value: 15
        reference: "15 weeks maternity benefits"

  parental_standard_weeks:
    description: "Maximum weeks of standard parental benefits."
    unit: weeks
    period: eternity
    label: "EI Parental Standard Weeks"
    reference: "EI Act Section 23"
    values:
      - date: 2017-12-03
        value: 40
        reference: "40 weeks standard (35 per parent max)"

  parental_extended_weeks:
    description: "Maximum weeks of extended parental benefits."
    unit: weeks
    period: eternity
    label: "EI Parental Extended Weeks"
    reference: "EI Act Section 23"
    values:
      - date: 2017-12-03
        value: 69
        reference: "69 weeks extended (61 per parent max)"

  sickness_weeks:
    description: "Maximum weeks of sickness benefits."
    unit: weeks
    period: eternity
    label: "EI Sickness Weeks"
    reference: "EI Act Section 12"
    values:
      - date: 2022-12-18
        value: 26
        reference: "Increased from 15 to 26 weeks"
      - date: 1996-01-01
        value: 15
        reference: "15 weeks sickness benefits"

  regular_max_weeks:
    description: "Maximum weeks of regular EI benefits."
    unit: weeks
    period: eternity
    label: "EI Regular Max Weeks"
    reference: "EI Act Section 12"
    values:
      - date: 1996-01-01
        value: 45
        reference: "Maximum 45 weeks regular benefits"

# Waiting period
waiting_period:
  weeks:
    description: "One-week waiting period before benefits start."
    unit: weeks
    period: eternity
    label: "EI Waiting Period"
    reference: "EI Act Section 13"
    values:
      - date: 2017-01-01
        value: 1
        reference: "Reduced from 2 to 1 week"
      - date: 1996-01-01
        value: 2
        reference: "Originally 2 weeks"

# Family supplement
family_supplement:
  income_threshold:
    description: "Family net income threshold for family supplement eligibility."
    unit: CAD
    period: year
    label: "EI Family Supplement Threshold"
    reference: "EI Act Section 16"
    values:
      - date: 2024-01-01
        value: 25921
        reference: "Linked to CCB threshold"
      - date: 2023-01-01
        value: 24863
        reference: "Linked to CCB threshold"
