# Climate Action Incentive Payment Parameters
# Income Tax Act Section 122.8
#
# CAIP is a tax-free payment to help offset the cost of federal carbon pricing.
# Only available to residents of provinces that use the federal carbon pricing backstop.
#
# Reference: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/cai-payment.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/section-122.8.html

description: "Climate Action Incentive Payment (CAIP) is a tax-free quarterly payment to help offset the cost of the federal carbon pricing system for families in eligible provinces."

# Province amounts - vary by province
# Ontario amounts
ontario:
  individual:
    description: "Base CAIP amount for an individual resident of Ontario."
    unit: CAD
    period: year
    label: "CAIP Ontario Individual"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 280
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 244
        reference: "CRA CAIP 2023-2024"
      - date: 2022-04-01
        value: 186
        reference: "CRA CAIP 2022-2023"

  spouse:
    description: "Additional CAIP amount for a spouse or common-law partner in Ontario."
    unit: CAD
    period: year
    label: "CAIP Ontario Spouse"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 140
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 122
        reference: "CRA CAIP 2023-2024"

  child:
    description: "CAIP amount for each child under 19 in Ontario."
    unit: CAD
    period: year
    label: "CAIP Ontario Child"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 70
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 61
        reference: "CRA CAIP 2023-2024"

# Alberta amounts
alberta:
  individual:
    description: "Base CAIP amount for an individual resident of Alberta."
    unit: CAD
    period: year
    label: "CAIP Alberta Individual"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 225
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 193
        reference: "CRA CAIP 2023-2024"

  spouse:
    description: "Additional CAIP amount for a spouse or common-law partner in Alberta."
    unit: CAD
    period: year
    label: "CAIP Alberta Spouse"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 112.50
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 96.50
        reference: "CRA CAIP 2023-2024"

  child:
    description: "CAIP amount for each child under 19 in Alberta."
    unit: CAD
    period: year
    label: "CAIP Alberta Child"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 56.25
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 48.25
        reference: "CRA CAIP 2023-2024"

# Saskatchewan amounts
saskatchewan:
  individual:
    description: "Base CAIP amount for an individual resident of Saskatchewan."
    unit: CAD
    period: year
    label: "CAIP Saskatchewan Individual"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 376
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 340
        reference: "CRA CAIP 2023-2024"

  spouse:
    description: "Additional CAIP amount for a spouse or common-law partner in Saskatchewan."
    unit: CAD
    period: year
    label: "CAIP Saskatchewan Spouse"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 188
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 170
        reference: "CRA CAIP 2023-2024"

  child:
    description: "CAIP amount for each child under 19 in Saskatchewan."
    unit: CAD
    period: year
    label: "CAIP Saskatchewan Child"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 94
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 85
        reference: "CRA CAIP 2023-2024"

# Manitoba amounts
manitoba:
  individual:
    description: "Base CAIP amount for an individual resident of Manitoba."
    unit: CAD
    period: year
    label: "CAIP Manitoba Individual"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 225
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 193
        reference: "CRA CAIP 2023-2024"

  spouse:
    description: "Additional CAIP amount for a spouse or common-law partner in Manitoba."
    unit: CAD
    period: year
    label: "CAIP Manitoba Spouse"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 112.50
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 96.50
        reference: "CRA CAIP 2023-2024"

  child:
    description: "CAIP amount for each child under 19 in Manitoba."
    unit: CAD
    period: year
    label: "CAIP Manitoba Child"
    reference: "ITA 122.8 / Schedule 14"
    values:
      - date: 2024-04-01
        value: 56.25
        reference: "CRA CAIP 2024-2025"
      - date: 2023-04-01
        value: 48.25
        reference: "CRA CAIP 2023-2024"

# Rural supplement (applies to all provinces)
rural_supplement:
  rate:
    description: "Additional percentage for residents of rural or small communities."
    unit: rate
    period: year
    label: "CAIP Rural Supplement Rate"
    reference: "ITA 122.8"
    values:
      - date: 2021-04-01
        value: 0.20
        reference: "20% rural supplement"
      - date: 2019-04-01
        value: 0.10
        reference: "10% rural supplement originally"

# Eligible provinces
eligible_provinces:
  description: "Provinces where CAIP applies (those using federal carbon pricing backstop)."
  values:
    - date: 2024-04-01
      provinces: ["ON", "AB", "SK", "MB"]
      reference: "CRA CAIP eligible provinces 2024-2025"
    - date: 2023-04-01
      provinces: ["ON", "AB", "SK", "MB"]
      reference: "CRA CAIP eligible provinces 2023-2024"
