# Canada Child Benefit Parameters
# Income Tax Act Section 122.61
#
# Reference: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-payment-amounts.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/section-122.61.html

description: "Canada Child Benefit (CCB) is a tax-free monthly payment to eligible families to help with the cost of raising children under 18."

# Maximum annual benefit amounts
max_amount:
  under_6:
    description: "Maximum annual CCB amount for each qualified dependant under age 6."
    unit: CAD
    period: year
    label: "CCB Maximum (Under 6)"
    reference: "ITA 122.61(1)(a)"
    values:
      - date: 2024-07-01
        value: 7787
        reference: "CRA CCB Payment Amounts 2024-2025"
      - date: 2023-07-01
        value: 7437
        reference: "CRA CCB Payment Amounts 2023-2024"
      - date: 2022-07-01
        value: 6997
        reference: "CRA CCB Payment Amounts 2022-2023"
      - date: 2021-07-01
        value: 6833
        reference: "CRA CCB Payment Amounts 2021-2022"
      - date: 2020-07-01
        value: 6765
        reference: "CRA CCB Payment Amounts 2020-2021"
      - date: 2019-07-01
        value: 6639
        reference: "CRA CCB Payment Amounts 2019-2020"
      - date: 2018-07-01
        value: 6496
        reference: "CRA CCB Payment Amounts 2018-2019"
      - date: 2017-07-01
        value: 6400
        reference: "CRA CCB Payment Amounts 2017-2018"
      - date: 2016-07-01
        value: 6400
        reference: "CCB introduction"

  age_6_to_17:
    description: "Maximum annual CCB amount for each qualified dependant aged 6 to 17."
    unit: CAD
    period: year
    label: "CCB Maximum (Age 6-17)"
    reference: "ITA 122.61(1)(a)"
    values:
      - date: 2024-07-01
        value: 6570
        reference: "CRA CCB Payment Amounts 2024-2025"
      - date: 2023-07-01
        value: 6275
        reference: "CRA CCB Payment Amounts 2023-2024"
      - date: 2022-07-01
        value: 5903
        reference: "CRA CCB Payment Amounts 2022-2023"
      - date: 2021-07-01
        value: 5765
        reference: "CRA CCB Payment Amounts 2021-2022"
      - date: 2020-07-01
        value: 5708
        reference: "CRA CCB Payment Amounts 2020-2021"
      - date: 2019-07-01
        value: 5602
        reference: "CRA CCB Payment Amounts 2019-2020"
      - date: 2018-07-01
        value: 5481
        reference: "CRA CCB Payment Amounts 2018-2019"
      - date: 2017-07-01
        value: 5400
        reference: "CRA CCB Payment Amounts 2017-2018"
      - date: 2016-07-01
        value: 5400
        reference: "CCB introduction"

# Income thresholds for reduction
income_threshold:
  first:
    description: "Adjusted family net income threshold above which the first reduction rate applies."
    unit: CAD
    period: year
    label: "CCB First Income Threshold"
    reference: "ITA 122.61(1)(a)"
    values:
      - date: 2024-07-01
        value: 36502
        reference: "CRA CCB Payment Amounts 2024-2025"
      - date: 2023-07-01
        value: 34863
        reference: "CRA CCB Payment Amounts 2023-2024"
      - date: 2022-07-01
        value: 32797
        reference: "CRA CCB Payment Amounts 2022-2023"
      - date: 2021-07-01
        value: 32028
        reference: "CRA CCB Payment Amounts 2021-2022"
      - date: 2020-07-01
        value: 31711
        reference: "CRA CCB Payment Amounts 2020-2021"
      - date: 2019-07-01
        value: 31120
        reference: "CRA CCB Payment Amounts 2019-2020"
      - date: 2018-07-01
        value: 30450
        reference: "CRA CCB Payment Amounts 2018-2019"
      - date: 2017-07-01
        value: 30000
        reference: "CRA CCB Payment Amounts 2017-2018"
      - date: 2016-07-01
        value: 30000
        reference: "CCB introduction"

  second:
    description: "Adjusted family net income threshold above which the second reduction rate applies."
    unit: CAD
    period: year
    label: "CCB Second Income Threshold"
    reference: "ITA 122.61(1)(a)"
    values:
      - date: 2024-07-01
        value: 79087
        reference: "CRA CCB Payment Amounts 2024-2025"
      - date: 2023-07-01
        value: 75537
        reference: "CRA CCB Payment Amounts 2023-2024"
      - date: 2022-07-01
        value: 71060
        reference: "CRA CCB Payment Amounts 2022-2023"
      - date: 2021-07-01
        value: 69395
        reference: "CRA CCB Payment Amounts 2021-2022"
      - date: 2020-07-01
        value: 68708
        reference: "CRA CCB Payment Amounts 2020-2021"
      - date: 2019-07-01
        value: 67426
        reference: "CRA CCB Payment Amounts 2019-2020"
      - date: 2018-07-01
        value: 65976
        reference: "CRA CCB Payment Amounts 2018-2019"
      - date: 2017-07-01
        value: 65000
        reference: "CRA CCB Payment Amounts 2017-2018"
      - date: 2016-07-01
        value: 65000
        reference: "CCB introduction"

# Reduction rates by number of children
reduction_rate:
  first_zone:
    one_child:
      description: "Reduction rate applied to AFNI in the first reduction zone for families with one child."
      unit: rate
      period: year
      label: "CCB First Zone Rate (1 child)"
      reference: "ITA 122.61(1)(a)"
      values:
        - date: 2016-07-01
          value: 0.07
          reference: "ITA 122.61(1)(a)(ii)"

    two_plus_children:
      description: "Reduction rate applied to AFNI in the first reduction zone for families with two or more children."
      unit: rate
      period: year
      label: "CCB First Zone Rate (2+ children)"
      reference: "ITA 122.61(1)(a)"
      values:
        - date: 2016-07-01
          value: 0.135
          reference: "ITA 122.61(1)(a)(ii)"

  second_zone:
    one_child:
      description: "Reduction rate applied to AFNI in the second reduction zone for families with one child."
      unit: rate
      period: year
      label: "CCB Second Zone Rate (1 child)"
      reference: "ITA 122.61(1)(a)"
      values:
        - date: 2016-07-01
          value: 0.032
          reference: "ITA 122.61(1)(a)(iii)"

    two_plus_children:
      description: "Reduction rate applied to AFNI in the second reduction zone for families with two or more children."
      unit: rate
      period: year
      label: "CCB Second Zone Rate (2+ children)"
      reference: "ITA 122.61(1)(a)"
      values:
        - date: 2016-07-01
          value: 0.057
          reference: "ITA 122.61(1)(a)(iii)"

# Age thresholds
age_threshold:
  young_child:
    description: "Age below which a child qualifies for the higher CCB amount."
    unit: years
    period: eternity
    label: "Young Child Age Threshold"
    reference: "ITA 122.6 definition of 'qualified dependant'"
    values:
      - date: 2016-07-01
        value: 6
        reference: "ITA 122.61(1)(a)"

  maximum:
    description: "Maximum age for a qualified dependant (child must be under this age)."
    unit: years
    period: eternity
    label: "Maximum Child Age"
    reference: "ITA 122.6 definition of 'qualified dependant'"
    values:
      - date: 2016-07-01
        value: 18
        reference: "ITA 122.6"
