# Old Age Security Parameters
# Old Age Security Act (R.S.C., 1985, c. O-9)
#
# Reference: https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/O-9/

description: "Old Age Security (OAS) is a monthly payment available to seniors aged 65 and older. The Guaranteed Income Supplement (GIS) provides additional income to low-income OAS recipients."

# OAS Pension amounts
oas:
  max_monthly_65_74:
    description: "Maximum monthly OAS pension for individuals aged 65 to 74."
    unit: CAD
    period: month
    label: "OAS Maximum (65-74)"
    reference: "OAS Act Section 3"
    values:
      - date: 2024-01-01
        value: 713.34
        reference: "Service Canada OAS Jan-Mar 2024"
      - date: 2023-10-01
        value: 707.68
        reference: "Service Canada OAS Oct-Dec 2023"
      - date: 2023-07-01
        value: 698.60
        reference: "Service Canada OAS Jul-Sep 2023"
      - date: 2023-04-01
        value: 691.00
        reference: "Service Canada OAS Apr-Jun 2023"
      - date: 2023-01-01
        value: 687.56
        reference: "Service Canada OAS Jan-Mar 2023"

  max_monthly_75_plus:
    description: "Maximum monthly OAS pension for individuals aged 75 and older (10% bonus)."
    unit: CAD
    period: month
    label: "OAS Maximum (75+)"
    reference: "OAS Act Section 3, as amended July 2022"
    values:
      - date: 2024-01-01
        value: 784.67
        reference: "Service Canada OAS Jan-Mar 2024 (10% increase)"
      - date: 2023-10-01
        value: 778.45
        reference: "Service Canada OAS Oct-Dec 2023 (10% increase)"
      - date: 2023-07-01
        value: 768.46
        reference: "Service Canada OAS Jul-Sep 2023 (10% increase)"
      - date: 2022-07-01
        value: 756.32
        reference: "10% increase introduced July 2022"

  age_75_bonus_rate:
    description: "Additional percentage for OAS recipients aged 75 and older."
    unit: rate
    period: eternity
    label: "OAS 75+ Bonus Rate"
    reference: "OAS Act as amended 2022"
    values:
      - date: 2022-07-01
        value: 0.10
        reference: "10% increase for 75+ introduced July 2022"
      - date: 1952-01-01
        value: 0
        reference: "No bonus before July 2022"

# Residence requirements
residence:
  minimum_years:
    description: "Minimum years of residence in Canada after age 18 to qualify for OAS."
    unit: years
    period: eternity
    label: "OAS Minimum Residence"
    reference: "OAS Act Section 3(2)"
    values:
      - date: 1952-01-01
        value: 10
        reference: "OAS Act Section 3(2)"

  full_pension_years:
    description: "Years of residence in Canada required for full OAS pension."
    unit: years
    period: eternity
    label: "OAS Full Pension Residence"
    reference: "OAS Act Section 3(1)"
    values:
      - date: 1952-01-01
        value: 40
        reference: "OAS Act Section 3(1)"

# Age requirements
age:
  minimum:
    description: "Minimum age to receive OAS pension."
    unit: years
    period: eternity
    label: "OAS Minimum Age"
    reference: "OAS Act Section 3"
    values:
      - date: 1952-01-01
        value: 65
        reference: "OAS Act Section 3"

  bonus_threshold:
    description: "Age at which the 10% OAS bonus begins."
    unit: years
    period: eternity
    label: "OAS Bonus Age"
    reference: "OAS Act as amended 2022"
    values:
      - date: 2022-07-01
        value: 75
        reference: "10% increase for 75+ introduced July 2022"

# OAS Recovery Tax (clawback)
recovery_tax:
  threshold:
    description: "Individual net income threshold above which OAS recovery tax applies."
    unit: CAD
    period: year
    label: "OAS Recovery Threshold"
    reference: "ITA 180.2"
    values:
      - date: 2024-01-01
        value: 86912
        reference: "ITA 180.2 for 2024"
      - date: 2023-01-01
        value: 81761
        reference: "ITA 180.2 for 2023"
      - date: 2022-01-01
        value: 79845
        reference: "ITA 180.2 for 2022"

  rate:
    description: "Rate at which OAS is clawed back for income above threshold."
    unit: rate
    period: eternity
    label: "OAS Recovery Rate"
    reference: "ITA 180.2"
    values:
      - date: 1989-01-01
        value: 0.15
        reference: "ITA 180.2 - 15%"

# GIS amounts
gis:
  max_monthly_single:
    description: "Maximum monthly GIS for a single pensioner (including widowed)."
    unit: CAD
    period: month
    label: "GIS Maximum (Single)"
    reference: "OAS Act Section 12"
    values:
      - date: 2024-01-01
        value: 1065.47
        reference: "Service Canada GIS Jan-Mar 2024"
      - date: 2023-10-01
        value: 1057.01
        reference: "Service Canada GIS Oct-Dec 2023"
      - date: 2023-07-01
        value: 1043.45
        reference: "Service Canada GIS Jul-Sep 2023"

  max_monthly_couple:
    description: "Maximum monthly GIS for each spouse when both receive full OAS."
    unit: CAD
    period: month
    label: "GIS Maximum (Couple)"
    reference: "OAS Act Section 12"
    values:
      - date: 2024-01-01
        value: 641.35
        reference: "Service Canada GIS Jan-Mar 2024"
      - date: 2023-10-01
        value: 636.26
        reference: "Service Canada GIS Oct-Dec 2023"
      - date: 2023-07-01
        value: 628.10
        reference: "Service Canada GIS Jul-Sep 2023"

  reduction_rate:
    description: "Rate at which GIS is reduced for income above exemptions."
    unit: rate
    period: eternity
    label: "GIS Reduction Rate"
    reference: "OAS Act Section 12"
    values:
      - date: 1967-01-01
        value: 0.50
        reference: "50 cents reduction per dollar of income"

  employment_income_exemption:
    description: "Annual employment income fully exempt from GIS income test."
    unit: CAD
    period: year
    label: "GIS Employment Exemption"
    reference: "OAS Regulations"
    values:
      - date: 2020-07-01
        value: 5000
        reference: "Enhanced employment exemption 2020"

  employment_income_partial_exemption:
    description: "Employment income partially exempt (50%) from GIS above full exemption."
    unit: CAD
    period: year
    label: "GIS Employment Partial Exemption"
    reference: "OAS Regulations"
    values:
      - date: 2020-07-01
        value: 10000
        reference: "Additional $10,000 at 50% exemption"

# Allowance amounts
allowance:
  max_monthly:
    description: "Maximum monthly Allowance for spouse of GIS recipient aged 60-64."
    unit: CAD
    period: month
    label: "Allowance Maximum"
    reference: "OAS Act Section 19"
    values:
      - date: 2024-01-01
        value: 1354.69
        reference: "Service Canada Allowance Jan-Mar 2024"
      - date: 2023-10-01
        value: 1343.92
        reference: "Service Canada Allowance Oct-Dec 2023"

  survivor_max_monthly:
    description: "Maximum monthly Allowance for the Survivor (widow/widower aged 60-64)."
    unit: CAD
    period: month
    label: "Survivor Allowance Maximum"
    reference: "OAS Act Section 21"
    values:
      - date: 2024-01-01
        value: 1614.89
        reference: "Service Canada Survivor Allowance Jan-Mar 2024"
      - date: 2023-10-01
        value: 1602.04
        reference: "Service Canada Survivor Allowance Oct-Dec 2023"

  age_minimum:
    description: "Minimum age for Allowance eligibility."
    unit: years
    period: eternity
    label: "Allowance Minimum Age"
    reference: "OAS Act Section 19"
    values:
      - date: 1975-01-01
        value: 60
        reference: "OAS Act Section 19"

  age_maximum:
    description: "Maximum age for Allowance (converts to OAS at 65)."
    unit: years
    period: eternity
    label: "Allowance Maximum Age"
    reference: "OAS Act Section 19"
    values:
      - date: 1975-01-01
        value: 64
        reference: "OAS Act Section 19"
