# Ontario Works Parameters
# Ontario Works Act, 1997, O. Reg. 134/98
#
# Reference: https://www.ontario.ca/page/ontario-works
# Legal: https://www.ontario.ca/laws/regulation/980134

description: "Ontario Works (OW) provides financial assistance to eligible residents of Ontario to help with basic living expenses and shelter costs."

# Basic needs allowance
basic_needs:
  single:
    description: "Monthly basic needs allowance for a single person."
    unit: CAD
    period: month
    label: "OW Basic Needs (Single)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 390
        reference: "2024 rates"
      - date: 2023-01-01
        value: 390
        reference: "2023 rates"
      - date: 2022-11-01
        value: 390
        reference: "5% increase Nov 2022"
      - date: 2018-09-01
        value: 343
        reference: "2018 rates"

  couple:
    description: "Monthly basic needs allowance for a couple."
    unit: CAD
    period: month
    label: "OW Basic Needs (Couple)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 629
        reference: "2024 rates"
      - date: 2022-11-01
        value: 629
        reference: "5% increase Nov 2022"

  first_child_0_12:
    description: "Additional basic needs for first child aged 0-12."
    unit: CAD
    period: month
    label: "OW Basic Needs (Child 0-12)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 217
        reference: "2024 rates"

  first_child_13_17:
    description: "Additional basic needs for first child aged 13-17."
    unit: CAD
    period: month
    label: "OW Basic Needs (Child 13-17)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 247
        reference: "2024 rates"

  additional_child_0_12:
    description: "Additional basic needs for each additional child aged 0-12."
    unit: CAD
    period: month
    label: "OW Basic Needs (Additional Child 0-12)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 189
        reference: "2024 rates"

  additional_child_13_17:
    description: "Additional basic needs for each additional child aged 13-17."
    unit: CAD
    period: month
    label: "OW Basic Needs (Additional Child 13-17)"
    reference: "O. Reg. 134/98, Schedule 1"
    values:
      - date: 2024-01-01
        value: 215
        reference: "2024 rates"

# Maximum shelter allowance
max_shelter:
  single:
    description: "Maximum monthly shelter allowance for a single person."
    unit: CAD
    period: month
    label: "OW Max Shelter (Single)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 390
        reference: "2024 rates"
      - date: 2022-11-01
        value: 390
        reference: "5% increase Nov 2022"

  couple:
    description: "Maximum monthly shelter allowance for a couple."
    unit: CAD
    period: month
    label: "OW Max Shelter (Couple)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 642
        reference: "2024 rates"

  family_3:
    description: "Maximum monthly shelter allowance for family of 3."
    unit: CAD
    period: month
    label: "OW Max Shelter (Family 3)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 697
        reference: "2024 rates"

  family_4:
    description: "Maximum monthly shelter allowance for family of 4."
    unit: CAD
    period: month
    label: "OW Max Shelter (Family 4)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 756
        reference: "2024 rates"

  family_5:
    description: "Maximum monthly shelter allowance for family of 5."
    unit: CAD
    period: month
    label: "OW Max Shelter (Family 5)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 815
        reference: "2024 rates"

  family_6_plus:
    description: "Maximum monthly shelter allowance for family of 6 or more."
    unit: CAD
    period: month
    label: "OW Max Shelter (Family 6+)"
    reference: "O. Reg. 134/98, Schedule 2"
    values:
      - date: 2024-01-01
        value: 844
        reference: "2024 rates"

# Earnings exemption
earnings_exemption:
  rate:
    description: "Percentage of employment earnings exempt from income calculation."
    unit: rate
    period: eternity
    label: "OW Earnings Exemption Rate"
    reference: "O. Reg. 134/98, Section 49"
    values:
      - date: 2013-09-01
        value: 0.50
        reference: "50% exemption introduced"

  flat_exemption:
    description: "Flat monthly earnings exemption amount."
    unit: CAD
    period: month
    label: "OW Flat Earnings Exemption"
    reference: "O. Reg. 134/98"
    values:
      - date: 2024-01-01
        value: 200
        reference: "First $200 fully exempt"

# Asset limits
asset_limit:
  single:
    description: "Maximum liquid assets for a single person."
    unit: CAD
    period: eternity
    label: "OW Asset Limit (Single)"
    reference: "O. Reg. 134/98, Section 39"
    values:
      - date: 2017-09-01
        value: 10000
        reference: "Asset limit increase"
      - date: 1998-01-01
        value: 2500
        reference: "Original limit"

  couple:
    description: "Maximum liquid assets for a couple."
    unit: CAD
    period: eternity
    label: "OW Asset Limit (Couple)"
    reference: "O. Reg. 134/98, Section 39"
    values:
      - date: 2017-09-01
        value: 15000
        reference: "Asset limit increase"

  family_3_plus:
    description: "Maximum liquid assets for family of 3 or more."
    unit: CAD
    period: eternity
    label: "OW Asset Limit (Family)"
    reference: "O. Reg. 134/98, Section 39"
    values:
      - date: 2017-09-01
        value: 20000
        reference: "Asset limit increase"

# Remote community supplement
remote_supplement:
  amount:
    description: "Monthly supplement for residents of designated remote communities."
    unit: CAD
    period: month
    label: "OW Remote Supplement"
    reference: "O. Reg. 134/98"
    values:
      - date: 2024-01-01
        value: 45
        reference: "2024 rates"

# Pregnancy/breastfeeding benefit
pregnancy_benefit:
  amount:
    description: "Monthly pregnancy/breastfeeding nutritional benefit."
    unit: CAD
    period: month
    label: "OW Pregnancy Benefit"
    reference: "O. Reg. 134/98"
    values:
      - date: 2024-01-01
        value: 50
        reference: "2024 rates"
