# BC Housing Benefit Parameters
# BC Rental Assistance Programs
#
# Reference: https://www.bchousing.org/housing-assistance/rental-assistance-programs
# Legal: BC Housing Management Commission Act

description: "The BC Housing Benefit provides monthly payments to help eligible families pay rent. SAFER provides similar assistance to seniors."

# Income thresholds by family size
income_threshold:
  family_1_child:
    description: "Maximum annual household income for family with 1 child."
    unit: CAD
    period: year
    label: "BC Housing Income Limit (1 child)"
    reference: "BC Housing RAP"
    values:
      - date: 2024-01-01
        value: 55000
        reference: "2024 limits"
      - date: 2023-01-01
        value: 52000
        reference: "2023 limits"

  family_2_children:
    description: "Maximum annual household income for family with 2 children."
    unit: CAD
    period: year
    label: "BC Housing Income Limit (2 children)"
    reference: "BC Housing RAP"
    values:
      - date: 2024-01-01
        value: 60000
        reference: "2024 limits"
      - date: 2023-01-01
        value: 57000
        reference: "2023 limits"

  family_3_children:
    description: "Maximum annual household income for family with 3 children."
    unit: CAD
    period: year
    label: "BC Housing Income Limit (3 children)"
    reference: "BC Housing RAP"
    values:
      - date: 2024-01-01
        value: 65000
        reference: "2024 limits"

  family_4_plus_children:
    description: "Maximum annual household income for family with 4+ children."
    unit: CAD
    period: year
    label: "BC Housing Income Limit (4+ children)"
    reference: "BC Housing RAP"
    values:
      - date: 2024-01-01
        value: 70000
        reference: "2024 limits"

# Maximum rent limits by region
max_rent:
  metro_vancouver:
    one_bedroom:
      description: "Maximum rent considered for one bedroom in Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (1BR Metro)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 1650
          reference: "2024 limits"

    two_bedroom:
      description: "Maximum rent considered for two bedroom in Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (2BR Metro)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 1950
          reference: "2024 limits"

    three_bedroom:
      description: "Maximum rent considered for three bedroom in Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (3BR Metro)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 2400
          reference: "2024 limits"

  other_bc:
    one_bedroom:
      description: "Maximum rent considered for one bedroom outside Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (1BR Other)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 1200
          reference: "2024 limits"

    two_bedroom:
      description: "Maximum rent considered for two bedroom outside Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (2BR Other)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 1400
          reference: "2024 limits"

    three_bedroom:
      description: "Maximum rent considered for three bedroom outside Metro Vancouver."
      unit: CAD
      period: month
      label: "BC Housing Max Rent (3BR Other)"
      reference: "BC Housing RAP"
      values:
        - date: 2024-01-01
          value: 1700
          reference: "2024 limits"

# Shelter cost ratio (percentage of income for rent)
shelter_cost_ratio:
  target:
    description: "Target percentage of income that should go to shelter costs."
    unit: rate
    period: eternity
    label: "BC Housing Target Shelter Ratio"
    reference: "BC Housing RAP"
    values:
      - date: 2000-01-01
        value: 0.30
        reference: "30% affordability target"

# Maximum monthly benefit
max_benefit:
  family:
    description: "Maximum monthly BC Housing Benefit for families."
    unit: CAD
    period: month
    label: "BC Housing Max Benefit"
    reference: "BC Housing RAP"
    values:
      - date: 2024-01-01
        value: 800
        reference: "2024 maximum"
      - date: 2023-01-01
        value: 750
        reference: "2023 maximum"

# SAFER (Shelter Aid for Elderly Renters) parameters
safer:
  age_minimum:
    description: "Minimum age for SAFER eligibility."
    unit: years
    period: eternity
    label: "SAFER Minimum Age"
    reference: "BC Housing SAFER"
    values:
      - date: 2000-01-01
        value: 60
        reference: "SAFER eligibility"

  income_threshold_single:
    description: "Maximum income for single senior SAFER."
    unit: CAD
    period: year
    label: "SAFER Income Limit (Single)"
    reference: "BC Housing SAFER"
    values:
      - date: 2024-01-01
        value: 37500
        reference: "2024 limits"

  income_threshold_couple:
    description: "Maximum income for senior couple SAFER."
    unit: CAD
    period: year
    label: "SAFER Income Limit (Couple)"
    reference: "BC Housing SAFER"
    values:
      - date: 2024-01-01
        value: 42000
        reference: "2024 limits"

  max_benefit:
    description: "Maximum monthly SAFER benefit."
    unit: CAD
    period: month
    label: "SAFER Maximum Benefit"
    reference: "BC Housing SAFER"
    values:
      - date: 2024-01-01
        value: 700
        reference: "2024 maximum"
