# GST/HST Credit Parameters
# Income Tax Act Section 122.5
#
# Reference: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/goods-services-tax-harmonized-sales-tax-gst-hst-credit.html
# Legal: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/section-122.5.html

description: "The GST/HST credit is a tax-free quarterly payment that helps individuals and families with low and modest incomes offset all or part of the GST or HST they pay."

# Credit amounts
amount:
  individual:
    description: "Base GST/HST credit amount for an eligible individual."
    unit: CAD
    period: year
    label: "GST/HST Individual Amount"
    reference: "ITA 122.5(3)(a)"
    values:
      - date: 2024-07-01
        value: 519
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 496
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 467
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 456
        reference: "CRA GST/HST Credit 2021-2022"
      - date: 2020-07-01
        value: 451
        reference: "CRA GST/HST Credit 2020-2021"
      - date: 2019-07-01
        value: 443
        reference: "CRA GST/HST Credit 2019-2020"

  spouse:
    description: "Additional GST/HST credit amount for a cohabiting spouse or common-law partner."
    unit: CAD
    period: year
    label: "GST/HST Spouse Amount"
    reference: "ITA 122.5(3)(b)"
    values:
      - date: 2024-07-01
        value: 519
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 496
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 467
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 456
        reference: "CRA GST/HST Credit 2021-2022"

  child:
    description: "GST/HST credit amount for each qualified dependant."
    unit: CAD
    period: year
    label: "GST/HST Child Amount"
    reference: "ITA 122.5(3)(c)"
    values:
      - date: 2024-07-01
        value: 171
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 163
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 153
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 150
        reference: "CRA GST/HST Credit 2021-2022"

  single_supplement:
    description: "Additional amount for eligible single individuals without a spouse or qualified dependant."
    unit: CAD
    period: year
    label: "GST/HST Single Supplement"
    reference: "ITA 122.5(3)(b.1)"
    values:
      - date: 2024-07-01
        value: 171
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 163
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 153
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 150
        reference: "CRA GST/HST Credit 2021-2022"

# Income thresholds
threshold:
  individual:
    description: "Adjusted net income threshold for single individuals above which the credit is reduced."
    unit: CAD
    period: year
    label: "GST/HST Individual Threshold"
    reference: "ITA 122.5(3)"
    values:
      - date: 2024-07-01
        value: 44324
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 42335
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 39826
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 38892
        reference: "CRA GST/HST Credit 2021-2022"

  family:
    description: "Adjusted family net income threshold for families above which the credit is reduced."
    unit: CAD
    period: year
    label: "GST/HST Family Threshold"
    reference: "ITA 122.5(3)"
    values:
      - date: 2024-07-01
        value: 58840
        reference: "CRA GST/HST Credit 2024-2025"
      - date: 2023-07-01
        value: 56201
        reference: "CRA GST/HST Credit 2023-2024"
      - date: 2022-07-01
        value: 52873
        reference: "CRA GST/HST Credit 2022-2023"
      - date: 2021-07-01
        value: 51634
        reference: "CRA GST/HST Credit 2021-2022"

# Phase-out rate
phaseout:
  rate:
    description: "Rate at which the GST/HST credit is reduced for income above the threshold."
    unit: rate
    period: year
    label: "GST/HST Phase-out Rate"
    reference: "ITA 122.5(3)"
    values:
      - date: 2000-01-01
        value: 0.05
        reference: "ITA 122.5(3)"

# Age requirements
age:
  minimum:
    description: "Minimum age to be eligible for the GST/HST credit (unless exempt)."
    unit: years
    period: eternity
    label: "GST/HST Minimum Age"
    reference: "ITA 122.5(2)"
    values:
      - date: 2000-01-01
        value: 19
        reference: "ITA 122.5(2)"

  child_maximum:
    description: "Maximum age for a child to be a qualified dependant for GST/HST credit."
    unit: years
    period: eternity
    label: "GST/HST Child Maximum Age"
    reference: "ITA 122.5(1) definition of 'qualified dependant'"
    values:
      - date: 2000-01-01
        value: 19
        reference: "ITA 122.5(1)"
